#!/usr/bin/env bash
function pglab () {
    restartEntrypoint=false
    if [[ "$1" == "help" ]]; then
        HELP="true"
    else
        while true; do
            case "$1" in
                project|group) command=$1; shift 1; break ;;
                --restart-entrypoint) restartEntrypoint=true; shift 1; break ;;
                --) addErrorMessage "Invalid option '$1'"; shift ;;
                -*|--*) addErrorMessage "Invalid option '$1'"; shift ;;
                * )
                    [ -z ${1+x} ] && break
                    addErrorMessage "Invalid command choice '$1', valid choices are: group, project"
                    break
                ;;
            esac
        done
    fi
    if [[ "$restartEntrypoint" == "true" ]]; then
        cmdRestartEntrypoint="pglab $@"
        bash -c "unset PGLAB_IGNORE_SCRIPT_AUTOSTART && export COMMAND_ENTRYPOINT=pglab && unset pglab && $cmdRestartEntrypoint"
        return $?
    fi
    if [[ "$HELP" == "true" ]]; then
        pglab-help
        return $?
    fi
    if [[ "$USAGE" == "true" ]]; then
        pglab-usage true true
        return $?
    fi

    if [[ "$command" != "" ]]; then
        use-command "$command" $@
        return $?
    fi
    check-dependencies-parameters "" true true
    if [ $? -ne 0 ]; then
        return $?
    fi

    echo
    pglab-raw-usage true true
    echo 
    echo "$commandEntrypoint: error: the following arguments are required: command"
    echo
}

function pglab-help () {
    echo "$(cat <<EOF
_COMMAND_ENTRYPOINT_()

NAME
       _COMMAND_ENTRYPOINT_ -

DESCRIPTION
       This Command Line Interface is a unified tools to manage your gitlab
       groups and projects in gitlab.com.

SYNOPSIS
          _COMMAND_ENTRYPOINT_ [options] <command> <subcommand> [parameters]

       Use command help for information on a specific command. The synopsis for
       each command shows its parameters and their usage. Optional  parameters
       are shown in square brackets.

HELP COMMAND
       help

       display this help and exit

AVAILABLE COMMANDS
       o group
       o project

EOF
)" | sed -E "s#_COMMAND_ENTRYPOINT_#$commandEntrypoint#g" | less
    return $?
}
[[ "$PGLAB_IGNORE_SCRIPT_AUTOSTART" != "true" ]] && commandExecAutostart="$(basename "$(readlink -f -- "$0")" | sed -E "s/ /-/g")"
if [[ "$commandExecAutostart" == "pglab" ]]; then
    [[ -L "$0" ]] \
        && SCRIPT_DIR=$(dirname -- "$( readlink -f -- "$0"; )") \
        || SCRIPT_DIR="$(dirname "${BASH_SOURCE[0]}")"
    source "${SCRIPT_DIR}/../common/all"
    $commandExecAutostart $@
    exit $?
fi