#!/usr/bin/env bash
function pglab-project-raw-get () {
    local gitlabToken="$1"
    local projectParam="$2"
    # Verify if parameter is number, then it is ID, or just full name
    if [ "$((( $projectParam )) 2>/dev/null && echo $? || echo $?)" -eq 0 ]; then
        SEARCH_BY="ID"
        PROJECT_ID="$projectParam"
        PROJECT_PATH="$PROJECT_ID"
    else
        SEARCH_BY="FULL_PATH"
        PROJECT_FULL_PATH_PARSED=$(echo "$projectParam" | sed -E "s/\//%2F/g")
        PROJECT_PATH="$PROJECT_FULL_PATH_PARSED"
    fi

    # Get project
    PROJECT_JSON=$(curl -s -f --header "Authorization: Bearer $gitlabToken" "https://gitlab.com/api/v4/projects/${PROJECT_PATH}")
    if [ $? -ne 0 ]; then
        echo -e "Error: failed request to get project"
        exit 1
    fi

    # Just format json to view it in terminal
    echo "$PROJECT_JSON" | jq .
}
function pglab-project-get () {
    if [[ "$1" == "help" ]]; then
        HELP="true"
    else
        while true; do
            case "$1" in
                --project=*) PROJECT_PARAM="${1#*=}"; shift 1 ;;
                --project) PROJECT_PARAM="$2";  shift 2 ;;
                --) addErrorMessage "Invalid option '$1'"; shift ;;
                -*|--*) addErrorMessage "Invalid option '$1'"; shift ;;
                * )
                    [ -z ${1+x} ] && break
                    addErrorMessage "Invalid parameter with value '$1'"
                    shift 1
                ;;
            esac
        done
    fi
    function verifyParameters () {
        if [ -z ${PROJECT_PARAM+x} ]; then
            addErrorMessage "Parameter project (--project) is required"
        fi
    }
    [[ "$HELP" == "true" ]] && pglab-project-get-help
    [[ "$USAGE" == "true" ]] && pglab-usage false false
    check-dependencies-parameters verifyParameters

    pglab-project-raw-get "$GITLAB_TOKEN" "$PROJECT_PARAM"
}

function pglab-project-get-help () {
    echo "$(cat <<EOF
_COMMAND_ENTRYPOINT_()

NAME
       _COMMAND_ENTRYPOINT_ -

DESCRIPTION
       Get detailed information for an Gitlab project.

SYNOPSIS
            _COMMAND_ENTRYPOINT_
          [help]
          --project <value>

HELP COMMAND
       help

       display this help and exit

OPTIONS
       --project (string|number)
          The project to get detailed information.

          This parameter value is the project ID if it is a number, or if
          it is not a number this parameter value is the project full path.

EOF
)" | sed -E "s#_COMMAND_ENTRYPOINT_#$commandEntrypoint#g" | less
    exit 0
}
[[ "$PGLAB_IGNORE_SCRIPT_AUTOSTART" != "true" ]] && commandExecAutostart="$(basename "$(readlink -f -- "$0")" | sed -E "s/ /-/g")"
if [[ "$commandExecAutostart" == "pglab-project-get" ]]; then
    [[ -L "$0" ]] \
        && SCRIPT_DIR=$(dirname -- "$( readlink -f -- "$0"; )") \
        || SCRIPT_DIR="$(dirname "${BASH_SOURCE[0]}")"
    source "${SCRIPT_DIR}/../common/all"
    $commandExecAutostart $@
fi