#!/usr/bin/env bash
function get-group () {
    local gitlabToken="$1"
    local groupParam="$2"
    # Verify if parameter is number, then it is ID, or just full name
    if [ "$((( $groupParam )) 2>/dev/null && echo $? || echo $?)" -eq 0 ]; then
        SEARCH_BY="ID"
        GROUP_ID="$groupParam"
        GROUP_PATH="$GROUP_ID"
    else
        SEARCH_BY="FULL_PATH"
        GROUP_FULL_PATH_PARSED=$(echo "$groupParam" | sed -E "s/\//%2F/g")
        GROUP_PATH="$GROUP_FULL_PATH_PARSED"
    fi

    # Get group
    GROUP_JSON=$(curl -s -f --header "Authorization: Bearer $gitlabToken" "https://gitlab.com/api/v4/groups/${GROUP_PATH}?with_projects=false")
    if [ $? -ne 0 ]; then
        echo -e "Error: failed request to get group"
        exit 1
    fi

    # Just format json to view it in terminal
    echo "$GROUP_JSON" | jq .
}
