apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: pet
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
        version: v1
    spec:
      containers:
      - name: app
        image: nginx
        imagePullPolicy: Always
        ports:
        - containerPort: 80
