#!/usr/bin/env bash
if [[ -L "$0" ]]; then
    SCRIPT_DIR=$(dirname -- "$( readlink -f -- "$0"; )")
else
    SCRIPT_DIR="$(dirname "${BASH_SOURCE[0]}")"
fi
BASE_GITLAB_SCRIPTS_DIR="$SCRIPT_DIR/../../../.."
source "${BASE_GITLAB_SCRIPTS_DIR}/common/start-scripts"
while true; do
    case "$1" in
        help) MANUAL="true"; break ;;
        --project=*) PROJECT_PARAM="${1#*=}"; shift 1 ;;
        --project) PROJECT_PARAM="$2";  shift 2 ;;
        -h|--help) HELP="true"; break ;;
        --) addErrorMessage "Invalid option '$1'"; shift ;;
        -*|--*) addErrorMessage "Invalid option '$1'"; shift ;;
        * )
            [ -z ${1+x} ] && break
            addErrorMessage "Invalid parameter with value '$1'"
            shift 1
        ;;
    esac
done
function verifyParameters () {
    if [ -z ${PROJECT_PARAM+x} ]; then
        addErrorMessage "Parameter project (--project) is required"
    fi
}
[[ "$MANUAL" == "true" ]] && manual-output
[[ "$HELP" == "true" ]] && help-output
check-dependencies-parameters verifyParameters

source "${SCRIPT_DIR}/functions"

get-project "$GITLAB_TOKEN" "$PROJECT_PARAM"