#!/usr/bin/env bash
function pglab-json-array-is-empty () {
  array="$1"

  arrayLength=$(echo "$array" | jq ".|length")
  if [[ $arrayLength -eq 0 ]]; then
    echo -n "true"
    return 0
  fi
  echo -n "false"
}