#!/usr/bin/env bash
function pglab-format-qtd-bytes () {
  qtdBytes="$1"
  formatOutput="$2"
  if [ "$formatOutput" == "B" ]; then
      bytesFormatMaking=$((($qtdBytes * 100)))
  elif [ "$formatOutput" == "KB" ]; then
      bytesFormatMaking=$((($qtdBytes * 100) /1024))
  elif [ "$formatOutput" == "MB" ]; then
      bytesFormatMaking=$((($qtdBytes * 100) /1024 / 1024))
  elif [ "$formatOutput" == "GB" ]; then
      bytesFormatMaking=$((($qtdBytes * 100) /1024 / 1024 / 1024))
  else
      bytesFormatted="${qtdBytes}"
  fi
  if [ -z ${bytesFormatted+x} ]; then
      qtdBytesInt="$(echo -n "${bytesFormatMaking}" | sed -E "s/^.{1,2}$/0/" | sed -E "s/.{2}$//")"
      qtdBytesIntDec="$(echo -n "${bytesFormatMaking}" | sed -E "s/^(.{1})$/0\1/" | sed -E "s/.+(.{2})$/\1/" | sed -E "s/0+$//")"
      if [ -z $qtdBytesIntDec ]; then
          bytesFormatted="${qtdBytesInt} ${formatOutput}"
      else
          bytesFormatted="${qtdBytesInt}.${qtdBytesIntDec} ${formatOutput}"
      fi
  fi
  echo -n "$bytesFormatted"
  return $?
}