#!/usr/bin/env bash
if [[ "$(command-entrypoint)" == "" ]]; then
    if [[ "$(type -P "$(basename ${0})")" == "${0}" ]]; then
        command-entrypoint "$(basename ${0})"
    else
        command-entrypoint "$0"
    fi
fi
commandEntrypoint=$(command-entrypoint)