#!/usr/bin/env bash
function use-command () {
    [[ -L "$0" ]] && SCRIPT_DIR=$(dirname -- "$( readlink -f -- "$0"; )")
    [[ ! -L "$0" ]] && SCRIPT_DIR="$(dirname "${BASH_SOURCE[0]}")"

    local command="$1"
    shift 1
    command-entrypoint "${command}"
    commandEntrypoint=$(command-entrypoint)

    unset command

    if [[ "$PGLAB_IGNORE_SCRIPT_AUTOSTART" == "true" ]]; then
        otherCmdsEntrypoint="$(echo "$(echo $commandEntrypoint | sed -E 's/([^ ]+)//')")"
        commandExec=$(echo "$(basename "$PGLAB_BASE_CMD_ENTRYPOINT")${otherCmdsEntrypoint}" | sed -E 's/ /-/g')
    else
        commandExec=$(echo "$commandEntrypoint" | sed -E 's/ /-/g')
    fi
    if [[ "$PGLAB_IGNORE_SCRIPT_AUTOSTART" != "true" ]]; then
        source "$SCRIPT_DIR/../commands/${commandExec}"
    fi
    $commandExec $@
    exit 0
}