#!/bin/bash

# If script dir is not in PATH, add it
SCRIPT_DIR=$(dirname -- "$( readlink -f -- "$0"; )")
echo "$PATH" | sed -E "s/:/\n/g" | grep -E "^${SCRIPT_DIR}$" > /dev/null && ADD_TO_PATH=false || ADD_TO_PATH=true
if [ "$ADD_TO_PATH" == "true" ]; then
    export PATH="${SCRIPT_DIR}:${PATH}"
fi

# Default values
DEFAULT_EXPR_GET_PROJECTS_JSON=".[]|{id,path_with_namespace,ssh_url_to_repo,web_url}"
DEFAULT_EXPR_GET_GROUP_JSON=".|{id,name,full_path}"
commandInfo=$(echo "COMMAND NAME
       $0 - get all projects from the group

SYNOPSIS
       $0 [OPTION]... GROUP

PARAMETERS
       GROUP [required]
              if it is a number, then it is the group id, it is used to get all projects in the group
              or user id, it is used to get all projects in user namespace
              but if it is not a number, then it is the group full path, it is used to get all projects in the group
              or username, it is used to get all projects in user namespace

OPTIONS
       --help
              display this help and exit

       --man
              display this help with less, like command man, then exit

VARIABLES
       GITLAB_TOKEN [required]
              a gitlab token used to iterate with Gitlab API endpoints

       EXPR_GET_GROUP_JSON [optional]
              jq filter applied in group to get only specified fields
              it needs the fields id and full_path
              default value = \"${DEFAULT_EXPR_GET_GROUP_JSON}\"

       EXPR_GET_PROJECTS_JSON [optional]
              jq filter applied in project list to get only specified fields
              default value = \"${DEFAULT_EXPR_GET_PROJECTS_JSON}\"\n")

if [ "$1" == "--help" ]; then
    echo -e "${commandInfo}"
    exit 0
fi

if [ "$1" == "--man" ]; then
    echo -e "${commandInfo}" | less
    exit 0
fi

# Verify required variables and parameters
errorParameters=""
if [ -z ${GITLAB_TOKEN+x} ]; then
    msgErrorItem="Variable GITLAB_TOKEN is required"
    errorParameters=$(echo "${errorParameters}\n${msgErrorItem}")
fi
if [ -z ${1+x} ]; then
    msgErrorItem="Parameter GROUP is required"
    errorParameters=$(echo "${errorParameters}\n${msgErrorItem}")
fi
if [ "$errorParameters" != "" ]; then
    errorParameters=$(echo "$errorParameters" | sed -E "s/^\\\n//")
    echo -e "Errors:\n$(echo -e "$errorParameters" | sed -E "s/^/ - /g")"
    echo -e "\nTry '$0 --help' or '$0 --man' for more information."
    exit 1
fi

# Getting default values to variables
if [ -z ${EXPR_GET_GROUP_JSON+x} ]; then
    export EXPR_GET_GROUP_JSON=$DEFAULT_EXPR_GET_GROUP_JSON
fi
if [ -z ${EXPR_GET_PROJECTS_JSON+x} ]; then
    export EXPR_GET_PROJECTS_JSON=$DEFAULT_EXPR_GET_PROJECTS_JSON
fi

# Verify if parameter is number, then it is ID, or just full name
if [ "$((( $1 )) 2>/dev/null && echo $? || echo $?)" -eq 0 ]; then
    SEARCH_BY="ID"
    GROUP_ID="$1"
    PATH_GROUP_PARAM="$GROUP_ID"
else
    SEARCH_BY="FULL_PATH"
    # Get group by group full path
    GROUP_FULL_PATH="$1"
    GROUP_FULL_PATH_PARSED=$(echo "$GROUP_FULL_PATH" | sed -E "s/\//%2F/g")
    PATH_GROUP_PARAM="$GROUP_FULL_PATH_PARSED"
fi

# Get all projects in the group
RESULT_ALL="[]"
per_page=1000
page=0
page_empty=false
while [ $page_empty != true ]; do
    page=$(($page+1))

    # Get projects in the group/user in the current page
    REQUEST_URL="https://gitlab.com/api/v4/groups/${PATH_GROUP_PARAM}/projects?per_page=$per_page&page=$page"
    RESULT=$(curl -s -f --header "Authorization: Bearer $GITLAB_TOKEN" "${REQUEST_URL}")
    # If failed try get projects in user namespace
    if [ $? -ne 0 ]; then
        REQUEST_URL="https://gitlab.com/api/v4/users/${PATH_GROUP_PARAM}/projects?per_page=$per_page&page=$page"
        RESULT=$(curl -s -f --header "Authorization: Bearer $GITLAB_TOKEN" "${REQUEST_URL}")
        if [ $? -ne 0 ]; then
            echo -e "Error: failed request to get projects in group and project"
            exit 1
        fi
    fi

    RESULT=$(echo "$RESULT" | jq "$EXPR_GET_PROJECTS_JSON" | jq --slurp '.')
    
    RESULT_ALL=$((echo "$RESULT_ALL" ; echo "$RESULT") | jq '. + input')

    # Verify if the current page doesn't have projects
    RESULT_LENGTH=$(echo "$RESULT" | jq ".|length")
    if [[ $RESULT_LENGTH -eq 0 ]]; then
        page_empty=true
    fi
done

# Just format json to view it in terminal
echo "$RESULT_ALL" | jq .