#!/usr/bin/env bash
function pglab-project-raw-list-by-group-in-page () {
    local gitlabToken="$1"
    local groupParam="$2"
    local getContainerRegistries="$3"
    local per_page="$4"
    local page="$5"
    local groupPath="$(pglab-get-number-or-url-encoded "$groupParam")"
    local requestUrl=""
    local listProjectsPage=""
    local exitCode=""
    # Try get projects in the group in the page
    requestUrl="https://gitlab.com/api/v4/groups/${groupPath}/projects?with_shared=false&per_page=$per_page&page=$page"
    listProjectsPage=$(curl -s -f --header "Authorization: Bearer $gitlabToken" "${requestUrl}")
    # If failed try get projects in group
    exitCode="$?"
    if [ $exitCode -ne 0 ]; then
        >&2 echo -e "Error: failed request to get projects in group"
        return "$exitCode"
    fi

    if [[ "$getContainerRegistries" == "true" ]]; then
        listProjectsPage="$(pglab-project-fill-container-registries "$listProjectsPage")"
        exitCode="$?"
        if [ $exitCode -ne 0 ]; then
            return "$exitCode"
        fi
    fi

    echo "$listProjectsPage" | jq .
    return $?
}