#!/usr/bin/env bash
function pglab-project-raw-list-by-user-in-page () {
    local gitlabToken="$1"
    local userParam="$2"
    local per_page="$3"
    local page="$4"
    local userPath="$(pglab-get-number-or-url-encoded "$userParam")"
    # Try get projects in the user in the page
    local requestUrl="https://gitlab.com/api/v4/users/${userPath}/projects?per_page=$per_page&page=$page"
    local listProjectsPage=$(curl -s -f --header "Authorization: Bearer $gitlabToken" "${requestUrl}")
    if [ $? -ne 0 ]; then
        exitCode=$?
        echo -e "Error: failed request to get projects in user"
        return $exitCode
    fi

    echo "$listProjectsPage" | jq .
}