#!/usr/bin/env bash
function pglab-project-raw-list-by-user () {
    local gitlabToken="$1"
    local userParam="$2"
    local getContainerRegistries="$3"
    local getContainerRegistryTags="$4"
    local getContainerRegistryDetailedTags="$5"
    local getRemoteMirrors="$6"
    local per_page="$7"
    local userPath="$(pglab-get-number-or-url-encoded "$userParam")"
    local listProjects="[]"
    local page=0
    local page_empty=false
    local listProjectsPage=""
    # Get all projects in the user
    while [ $page_empty != true ]; do
        page=$(($page+1))
        listProjectsPage=$(pglab-project-raw-list-by-user-in-page "$gitlabToken" "$userParam" "$getContainerRegistries" "$getContainerRegistryTags" "$getContainerRegistryDetailedTags" "$getRemoteMirrors" "$per_page" "$page")
        exitCode=$?
        if [ $exitCode -ne 0 ]; then
            return $exitCode
        fi
        listProjects=$(pglab-json-array-join "$listProjects" "$listProjectsPage")
        page_empty=$(pglab-json-array-is-empty "$listProjectsPage")
    done

    echo "$listProjects" | jq .
    return $?
}