#!/usr/bin/env bash
function pglab-project-raw-list-by-group () {
    local gitlabToken="$1"
    local groupParam="$2"
    local per_page="$3"
    local listProjects="[]"
    local page=0
    local page_empty=false
    local listProjectsPage=""
    # Get all projects in the group
    while [ $page_empty != true ]; do
        page=$(($page+1))
        listProjectsPage=$(pglab-project-raw-list-by-group-in-page "$gitlabToken" "$groupParam" "$per_page" "$page")
        exitCode=$?
        if [ $exitCode -ne 0 ]; then
            return $exitCode
        fi
        listProjects=$(pglab-json-array-join "$listProjects" "$listProjectsPage")
        page_empty=$(pglab-json-array-is-empty "$listProjectsPage")
    done

    echo "$listProjects" | jq .
}