#!/usr/bin/env bash
function pglab-project-list-help () {
    echo "$(cat <<EOF
_COMMAND_ENTRYPOINT_()

NAME
       _COMMAND_ENTRYPOINT_ -

DESCRIPTION
       Get list of projects by group, by user or by namespace (that is group or user in the same parameter)

SYNOPSIS
            _COMMAND_ENTRYPOINT_
          [help]
          [--group <value>]
          [--user <value>]
          [--namespace <value>]
          [--container-registries]
          [--container-registries-tags]
          [--container-registries-detailed-tags]
          [--recursive]
          [--per-page <value>]
          [--page <value>]

HELP COMMAND
       help

       display this help and exit

OPTIONS
       --group (string|number)
          The group to get its projects.

          This parameter value is the group ID if it is a number, or if
          it is not a number this parameter value is the group full path.

       --user (string|number)
          The user to get its projects.

          This parameter value is the user ID if it is a number, or if
          it is not a number this parameter value is the user full path.

       --namespace (string|number)
          The namespace (group or project) to get its projects.

          This parameter value is the namespace (group or project) ID if
          it is a number, or if it is not a number this parameter value
          is the namespace (group or project) full path.

       --container-registries
          If used, include project container registries

       --container-registries-tags
          If used, include project container registries with its tags

       --container-registries-detailed-tags
          If used, include project container registries with its detailed tags

       --recursive
          If used with --group or --namespace (namespace must be a 
          group), get group projects and its subgroup projects recursively.

EOF
)" | sed -E "s#_COMMAND_ENTRYPOINT_#$commandEntrypoint#g" | less
    return $?
}