#!/usr/bin/env bash
function pglab-project-raw-list-by-user-in-page () {
    local gitlabToken="$1"
    local userParam="$2"
    local getContainerRegistries="$3"
    local per_page="$4"
    local page="$5"
    local userPath="$(pglab-get-number-or-url-encoded "$userParam")"
    local requestUrl=""
    local listProjectsPage=""
    # Try get projects in the user in the page
    requestUrl="https://gitlab.com/api/v4/users/${userPath}/projects?per_page=$per_page&page=$page"
    listProjectsPage=$(curl -s -f --header "Authorization: Bearer $gitlabToken" "${requestUrl}")
    exitCode=$?
    if [ $exitCode -ne 0 ]; then
        >&2 echo -e "Error: failed request to get projects in user"
        return "$exitCode"
    fi

    if [[ "$getContainerRegistries" == "true" ]]; then
        listProjectsPage="$(pglab-project-fill-container-registries "$listProjectsPage")"
        exitCode="$?"
        if [ $exitCode -ne 0 ]; then
            return "$exitCode"
        fi
    fi

    echo "$listProjectsPage" | jq .
    return $?
}