#!/usr/bin/env bash
[[ -L "$0" ]] && SCRIPT_DIR=$(dirname -- "$( readlink -f -- "$0"; )")
[[ ! -L "$0" ]] && SCRIPT_DIR="$(dirname "${BASH_SOURCE[0]}")"
source "${SCRIPT_DIR}/common/all"

if [[ "$1" == "help" ]]; then
    HELP="true"
else
    while true; do
        case "$1" in
            project|group) command=$1; shift 1; break ;;
            --) addErrorMessage "Invalid option '$1'"; shift ;;
            -*|--*) addErrorMessage "Invalid option '$1'"; shift ;;
            * )
                [ -z ${1+x} ] && break
                addErrorMessage "Invalid command choice '$1', valid choices are: project"
                shift 1
            ;;
        esac
    done
fi
[[ "$HELP" == "true" ]] && cat "$SCRIPT_DIR/MANUAL.txt" | sed -E "s#_COMMAND_ENTRYPOINT_#$commandEntrypoint#g" | less && exit 0
[[ "$USAGE" == "true" ]] && pglab-usage true true
check-dependencies-parameters

[[ "$command" != "" ]] && use-command "$command" $@

echo
pglab-raw-usage true true
echo 
echo "$commandEntrypoint: error: the following arguments are required: command"
echo