#!/usr/bin/env bash
if [[ -L "$0" ]]; then
    SCRIPT_DIR=$(dirname -- "$( readlink -f -- "$0"; )")
else
    SCRIPT_DIR="$(dirname "${BASH_SOURCE[0]}")"
fi
BASE_GITLAB_SCRIPTS_DIR="$SCRIPT_DIR"
source "${BASE_GITLAB_SCRIPTS_DIR}/common/start-scripts"

if [[ "$1" == "help" ]]; then
    HELP="true"
else
    while true; do
        case "$1" in
            project|group) command=$1; shift 1; break ;;
            --) addErrorMessage "Invalid option '$1'"; shift ;;
            -*|--*) addErrorMessage "Invalid option '$1'"; shift ;;
            * )
                [ -z ${1+x} ] && break
                addErrorMessage "Invalid command choice '$1', valid choices are: project"
                shift 1
            ;;
        esac
    done
fi
[[ "$HELP" == "true" ]] && manual-output
[[ "$USAGE" == "true" ]] && pglab-usage true true
check-dependencies-parameters

[[ "$command" != "" ]] && use-command "$command" $@

echo
usage
echo 
echo "$commandEntrypoint: error: the following arguments are required: command"
echo